### ISSUE TITLE
[1.12.2] Heads in Creative Tab

### ISSUE THREAD

**Issue by drakray** [Shinoow/AbyssalCraft-Heads#1]
#### Description:

Heads are visible in (almost) every Creative Tab (also Abyssal Zombie head in Delete slot)

#### Crash report:

N/A

----

#### Affected versions ("latest" is **NOT** a version):
- Minecraft: 1.12.2
- Forge: 2707
- AbyssalCraft Heads: 2.0.0
- AbyssalCraft: 1.9.4.9

#### Latest log file for when the issue was present:

[latest.log.txt](https://github.com/Shinoow/AbyssalCraft-Heads/files/2078517/latest.log.txt)

**Comment by Shinoow** [comment]
Oops, missed an if statement there. The head being in the delete slot is also caused by the same thing as the heads being in more tabs outside of their own.

**Comment by drakray** [comment]
While you're in the block code, could you take a sec to [implement Thaumcraft stabilization](https://github.com/Azanor/thaumcraft-api/blob/master/crafting/IInfusionStabiliser.java) please?   :D
That'd be awesome! (I used ModTweaker to give aspect to each of your head, and I plan on making a couple of custom recipe to and from them, 'to' at least until they drop from their respective mob)

**Comment by Mike-U5** [comment]
I too used crafttweaker to make them drop from their respective mobs, so I would like to +1 the stabilization thing.

**Comment by Sketaful** [comment]
Ah. This is why it's good to check the issues tab before posting something. I noticed the problem with heads in every tab as well, but now I don't have to spam with new issue or posting in the comments section. ;P
